#---------------------------------- # Stage 1: Build Stage ----------------------------------

# Use Maven image with JDK 17
FROM maven:3.8.3-openjdk-17 AS builder

# Set working directory
WORKDIR /app

# Copy source code to the container
COPY . .

# Build the application while skipping tests
RUN mvn clean install -DskipTests=true

#-------------------------------------- # Stage 2: Deployment Stage  --------------------------------------

# Use a lightweight JDK runtime
FROM openjdk:17-alpine AS deployer

# Set working directory
WORKDIR /app

# Copy the JAR file from the build stage
COPY --from=builder /app/target/*.jar bankapp.jar

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "bankapp.jar"]

